version: '3'
services:
  gitapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/opt/project'
      - './logs:/opt/project/logs'
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_TOKEN=${GIT_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
    command: >
      sh -c "python /opt/project/main_code.py >> /opt/project/logs/console.log 2>&1"
    container_name: CodeLineMeter
    image: gitapp
