version: '3'
services:
  gitapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/opt/project'
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_TOKEN=${GIT_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    command: >
      sh -c "python /opt/project/main_code.py"